enabled-worlds:
  - world
item:
  trigger-materials:
    - ROSE_BUSH
  hotbar:
    enabled: true
    slot: 9
    name: "&c&lRosa de Gratitud"
    lore:
      - "&7Lanza esta rosa al agua para agradecer."
      - "&7Recibirás efectos y un mensaje especial."
detection:
  water-detection-window-seconds: 10
  cooldown-seconds: 3
  return-item-after-seconds: 3
effects:
  duration-seconds: 3
  particle-count: 40
  show-title: true
  particle-dust-type: REDSTONE
  particle-dust-color: "#FF0000"
  particle-dust-size: 1.5
  particle-splash-type: WATER_SPLASH
  sounds:
    - name: ENTITY_PLAYER_LEVELUP
      volume: 1.0
      pitch: 1.0
worldguard:
  enabled: true
  allowed-regions:
    - world
database:
  type: SQLITE #SQLITE or MYSQL
  file: gratitude.db
  host: localhost
  port: 3306
  name: gratitude
  user: root
  password: ""
  use-ssl: false
  params: ""
  pool-max-size: 10
  pool-min-idle: 2
  connection-timeout-ms: 10000
  leak-detection-threshold-ms: 0
