name: ${name}
version: ${version}
main: me.mapacheee.gratituderoses.GratitudeRosesPlugin
api-version: "1.21"
description: ${description}
authors: ["Mapacheee"]
website: ""
folia-supported: true
libraries:
  - org.xerial:sqlite-jdbc:3.46.0.0
  - com.mysql:mysql-connector-j:8.4.0
dependencies:
  - name: WinterCore
    optional: false
    bootstrap: false
    load: BEFORE
  - name: PlaceholderAPI
    optional: true
    bootstrap: false
    load: AFTER
  - name: WorldGuard
    optional: true
    bootstrap: false
    load: AFTER
permissions:
  gratituderoses.admin:
    description: access to admin commands
    default: op
