name: GratitudeRoses
version: 1.0.0
main: me.mapacheee.gratituderoses.GratitudeRosesPlugin
api-version: "1.21"
description: revenge lobby plugin
authors: ["Mapacheee"]
folia-supported: true
dependencies:
  server:
    WinterCore:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      required: false
    WorldGuard:
      required: false

permissions:
  gratituderoses.admin:
    description: access to admin commands
    default: op